export const products = [
	{
		id: 1,
		name: "Bakso",
		category: "Makanan",
		image: require("../assets/makanan/bakso.jpg"),
		price: 12000,
	},
	{
		id: 2,
		name: "Opro Ayam",
		category: "Makanan",
		image: require("../assets/makanan/lontong-opor-ayam.jpg"),
		price: 12000,
	},
	{
		id: 3,
		name: "Mie Goreng",
		category: "Makanan",
		image: require("../assets/makanan/mie-goreng.jpg"),
		price: 12000,
	},
	{
		id: 4,
		name: "Es Teh",
		category: "Minuman",
		image: require("../assets/minuman/es-teh.jpg"),
		price: 12000,
	},
	{
		id: 5,
		name: "Es Jeruk",
		category: "Minuman",
		image: require("../assets/minuman/es-jeruk.jpg"),
		price: 12000,
	},
	{
		id: 6,
		name: "Kentang Goreng",
		category: "Cemilan",
		image: require("../assets/cemilan/kentang-goreng.jpg"),
		price: 12000,
	},
	{
		id: 7,
		name: "Es Teh",
		category: "Makanan",
		image: require("../assets/makanan/sate-ayam.jpg"),
		price: 12000,
	},
	{
		id: 8,
		name: "Nasi Goreng",
		category: "Makanan",
		image: require("../assets/makanan/nasi-goreng-telor.jpg"),
		price: 12000,
	},
	{
		id: 9,
		name: "Opro Ayam",
		category: "Makanan",
		image: require("../assets/makanan/lontong-opor-ayam.jpg"),
		price: 12000,
	},
	{
		id: 10,
		name: "Mie Goreng",
		category: "Makanan",
		image: require("../assets/makanan/mie-goreng.jpg"),
		price: 12000,
	},
	{
		id: 11,
		name: "Opro Ayam",
		category: "Makanan",
		image: require("../assets/makanan/lontong-opor-ayam.jpg"),
		price: 12000,
	},
	{
		id: 12,
		name: "Mie Goreng",
		category: "Makanan",
		image: require("../assets/makanan/mie-goreng.jpg"),
		price: 12000,
	},
	{
		id: 13,
		name: "Mie Goreng",
		category: "Makanan",
		image: require("../assets/makanan/mie-goreng.jpg"),
		price: 12000,
	},
	{
		id: 14,
		name: "Opro Ayam",
		category: "Makanan",
		image: require("../assets/makanan/lontong-opor-ayam.jpg"),
		price: 12000,
	},
	{
		id: 15,
		name: "Mie Goreng",
		category: "Makanan",
		image: require("../assets/makanan/mie-goreng.jpg"),
		price: 12000,
	},
];
